-- db/migrations/001-core-baseline.sql
-- Regenerated: 2026-07-29 (this is the date the file's CONTENT was last regenerated from InitTables, not
-- an authorship/creation date — it moves every time this file is regenerated; see git log for history).
--
-- CORE BOOTSTRAP BASELINE. Creates the complete core-framework schema — the 10 FrameworkEntityTypes
-- tables (languages / files / file_translations / media_folders / users / roles / permissions /
-- user_roles / revisions / site_settings) plus their PKs, unique indexes, and hot-path indexes.
-- (Uniqueness is enforced via CREATE UNIQUE INDEX, not ADD CONSTRAINT UNIQUE — so pg_constraint shows
-- only PKs, matching InitTables.)
--
-- Machine-generated by running InitTables(FrameworkEntityTypes.All) against a scratch PostgreSQL
-- database and dumping the result with `pg_dump --schema-only`, then hand-hardened to be idempotent
-- (IF NOT EXISTS throughout; PKs inlined) and stripped of the pg_dump session preamble
-- (SET/SELECT pg_catalog.set_config lines, ownership statements, restrict/unrestrict markers).
--
-- This is the PRODUCTION bootstrap path: a downstream deploy applies it to an EMPTY database via
-- MigrationRunner (Database:MigrationsPath) with NO dependency on the Development-only InitTables.
-- In dev, InitTables has already created these tables and Database:MigrationsPath stays empty, so this
-- file is not run there; it is fully idempotent regardless, so a manual re-run against an already-current
-- database is a safe no-op.
--
-- SCOPE — CORE ONLY. Business/sample schema (the Blog demo) is deliberately NOT here. See
-- db/migrations/README.md ("Scope is core only" / "Downstream forks") for the full rationale and the
-- fork workflow. Never add business-table DDL to this core baseline.
--
-- For the timestamp-type convention (DB-7) and the identifier-naming convention (lowercase, unquoted,
-- SqlSugar-emitted index names kept verbatim so dev InitTables and this file agree) this DDL follows,
-- see db/migrations/README.md — duplicating those conventions here has previously gone stale; the README
-- is the single source of truth for them.
--
-- FOLDED HISTORY — this baseline supersedes and subsumes two prior scripts: 002-media-folders.sql (the
-- media_folders table + files.folderid) and 003-file-soft-delete.sql (files.deletedat/deletedby +
-- retiring the 'archived' status), reproduced here inline because InitTables generates them directly
-- from the current entity classes. 003 also carried a one-off data normalisation this file does NOT
-- reproduce: `UPDATE files SET deletedat = COALESCE(deletedat, now()), status = 'draft' WHERE status =
-- 'archived'`. That statement is a no-op on a fresh/empty database (the only case this file is ever
-- applied against — see FILENAME-KEYED TRACKING below), which is why its omission is safe here.
--
-- MEDIA_FOLDERS COLUMN ORDER — this file's `media_folders` physical column order follows entity
-- declaration order (InitTables/pg_dump), which differs from the order 002-media-folders.sql produced.
-- Functionally irrelevant (SqlSugar binds by column name, never ordinal position), but it means a
-- `pg_dump` of a database that received media_folders via the old 002 script is not textually comparable
-- to a fresh database built from this file.
--
-- FILENAME-KEYED TRACKING — READ BEFORE ASSUMING AN UPGRADE OF AN EXISTING DATABASE IS SAFE.
-- MigrationRunner (src/Struo.Infrastructure/Persistence/MigrationRunner.cs) tracks applied migrations by
-- FILENAME ONLY — no checksum, no content hash (see SelectPending and the `applied` set built from
-- `SELECT filename FROM schema_migrations`). This regeneration kept the pre-existing filename
-- `001-core-baseline.sql`, so:
--   - A FRESH/EMPTY database gets the complete current core schema (all 10 tables, including
--     media_folders and files.folderid/deletedat/deletedby) from this file alone. This is the only case
--     this template ships or supports.
--   - A database that had already recorded `001-core-baseline.sql` BEFORE this fold will NOT receive the
--     folded content when this file is redeployed over it: MigrationRunner sees the filename already
--     applied and skips the file entirely, permanently. Such a database is left without media_folders,
--     files.folderid, files.deletedat, and files.deletedby — redeploying this file does NOT fix that; the
--     database must be rebuilt from empty or caught up by hand.
--   - The forward rule: a change that must reach already-deployed databases belongs in a NEW `NNN-…`
--     file. Never edit the content of a filename that may already be recorded as applied anywhere —
--     MigrationRunner will never re-run it.
-- This repo is pre-release and private — no database predating this fold exists, so no catch-up script
-- ships with the template; a fork starting fresh gets the complete schema from `001` alone.

-- ----------------------------------------------------------------------------------------------------
-- Sequences (bigint identity PKs: languages, file_translations)
-- ----------------------------------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS public.languages_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE IF NOT EXISTS public.file_translations_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- ----------------------------------------------------------------------------------------------------
-- Tables
-- ----------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.languages (
    id        bigint                      NOT NULL DEFAULT nextval('public.languages_id_seq'::regclass),
    code      character varying(255)      NOT NULL,
    name      character varying(255)      NOT NULL,
    isdefault boolean                     NOT NULL,
    enabled   boolean                     NOT NULL,
    sort      integer                     NOT NULL,
    createdat timestamp without time zone NOT NULL,
    createdby uuid,
    updatedat timestamp without time zone NOT NULL,
    updatedby uuid,
    CONSTRAINT languages_pkey PRIMARY KEY (id)
);
ALTER SEQUENCE public.languages_id_seq OWNED BY public.languages.id;

CREATE TABLE IF NOT EXISTS public.files (
    id          uuid                        NOT NULL,
    storagekey  character varying(255)      NOT NULL,
    filename    character varying(255)      NOT NULL,
    contenttype character varying(255)      NOT NULL,
    size        bigint                      NOT NULL,
    width       integer,
    height      integer,
    status      character varying(255)      NOT NULL,
    folderid    uuid,
    deletedat   timestamp without time zone,
    deletedby   uuid,
    createdat   timestamp without time zone NOT NULL,
    createdby   uuid,
    updatedat   timestamp without time zone NOT NULL,
    updatedby   uuid,
    version     bigint                      NOT NULL,
    CONSTRAINT files_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.file_translations (
    id     bigint                 NOT NULL DEFAULT nextval('public.file_translations_id_seq'::regclass),
    fileid uuid                   NOT NULL,
    locale character varying(255) NOT NULL,
    title  character varying(255) DEFAULT NULL::character varying,
    alt    character varying(255) DEFAULT NULL::character varying,
    CONSTRAINT file_translations_pkey PRIMARY KEY (id)
);
ALTER SEQUENCE public.file_translations_id_seq OWNED BY public.file_translations.id;

CREATE TABLE IF NOT EXISTS public.media_folders (
    id        uuid                     NOT NULL,
    createdat timestamp with time zone NOT NULL,
    updatedat timestamp with time zone NOT NULL,
    name      character varying(255)   NOT NULL,
    parentid  uuid,
    createdby uuid,
    updatedby uuid,
    version   bigint                   NOT NULL,
    CONSTRAINT media_folders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users (
    id                    uuid                        NOT NULL,
    email                 character varying(255)      NOT NULL,
    password              character varying(255)      NOT NULL,
    name                  character varying(255)      DEFAULT NULL::character varying,
    isactive              boolean                     NOT NULL,
    accesstoken           character varying(255)      DEFAULT NULL::character varying,
    accesstokencreatedat  timestamp without time zone,
    accesstokenlastusedat timestamp without time zone,
    createdat             timestamp without time zone NOT NULL,
    createdby             uuid,
    updatedat             timestamp without time zone NOT NULL,
    updatedby             uuid,
    version               bigint                      NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles (
    id          uuid                        NOT NULL,
    name        character varying(255)      NOT NULL,
    issuperadmin boolean                    NOT NULL,
    description character varying(255)      DEFAULT NULL::character varying,
    createdat   timestamp without time zone NOT NULL,
    createdby   uuid,
    updatedat   timestamp without time zone NOT NULL,
    updatedby   uuid,
    version     bigint                      NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.permissions (
    id         uuid                        NOT NULL,
    roleid     uuid                        NOT NULL,
    collection character varying(255)      NOT NULL,
    canread    boolean                     NOT NULL,
    canwrite   boolean                     NOT NULL,
    candelete  boolean                     NOT NULL,
    createdat  timestamp without time zone NOT NULL,
    createdby  uuid,
    updatedat  timestamp without time zone NOT NULL,
    updatedby  uuid,
    version    bigint                      NOT NULL,
    CONSTRAINT permissions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_roles (
    id        uuid                        NOT NULL,
    userid    uuid                        NOT NULL,
    roleid    uuid                        NOT NULL,
    createdat timestamp without time zone NOT NULL,
    createdby uuid,
    updatedat timestamp without time zone NOT NULL,
    updatedby uuid,
    version   bigint                      NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.revisions (
    id             uuid                        NOT NULL,
    collectionname character varying(255)      NOT NULL,
    itemid         character varying(255)      NOT NULL,
    revisionnumber bigint                      NOT NULL,
    operation      character varying(255)      NOT NULL,
    snapshot       text                        NOT NULL,
    createdat      timestamp without time zone NOT NULL,
    createdby      uuid,
    CONSTRAINT revisions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.site_settings (
    id         uuid                     NOT NULL,
    brandname  text                     NOT NULL,
    logofileid uuid,
    updatedat  timestamp with time zone NOT NULL,
    updatedby  uuid,
    CONSTRAINT site_settings_pkey PRIMARY KEY (id)
);

-- ----------------------------------------------------------------------------------------------------
-- Unique constraints (as unique indexes — matches InitTables UniqueGroupNameList emission)
-- ----------------------------------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS index_file_translations_fileid_locale_unique
    ON public.file_translations USING btree (fileid, locale);
CREATE UNIQUE INDEX IF NOT EXISTS index_permissions_roleid_collection_unique
    ON public.permissions USING btree (roleid, collection);
CREATE UNIQUE INDEX IF NOT EXISTS index_revisions_collectionname_itemid_revisionnumber_unique
    ON public.revisions USING btree (collectionname, itemid, revisionnumber);
CREATE UNIQUE INDEX IF NOT EXISTS index_roles_name_unique
    ON public.roles USING btree (name);
CREATE UNIQUE INDEX IF NOT EXISTS index_user_roles_userid_roleid_unique
    ON public.user_roles USING btree (userid, roleid);
CREATE UNIQUE INDEX IF NOT EXISTS index_users_accesstoken_unique
    ON public.users USING btree (accesstoken);
CREATE UNIQUE INDEX IF NOT EXISTS index_users_email_unique
    ON public.users USING btree (email);

-- ----------------------------------------------------------------------------------------------------
-- Hot-path btree indexes
-- ----------------------------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS ix_files_folderid
    ON public.files USING btree (folderid);
CREATE INDEX IF NOT EXISTS ix_media_folders_parentid
    ON public.media_folders USING btree (parentid);
CREATE INDEX IF NOT EXISTS ix_permissions_roleid
    ON public.permissions USING btree (roleid);
CREATE INDEX IF NOT EXISTS ix_user_roles_roleid
    ON public.user_roles USING btree (roleid);
CREATE INDEX IF NOT EXISTS ix_user_roles_userid
    ON public.user_roles USING btree (userid);
