<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Struo.Domain\Struo.Domain.csproj" />
    <ProjectReference Include="..\..\src\Struo.Application\Struo.Application.csproj" />
    <ProjectReference Include="..\..\src\Struo.Infrastructure\Struo.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Struo.Api\Struo.Api.csproj" />
    <ProjectReference Include="..\..\samples\Struo.Sample.Blog\Struo.Sample.Blog.csproj" />
  </ItemGroup>

</Project>
