<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Struo.Domain\Struo.Domain.csproj" />
    <ProjectReference Include="..\..\src\Struo.Infrastructure\Struo.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SqlSugarCore" />
  </ItemGroup>

</Project>
